# Copyright 2023 Enzo Venturi. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default:
  image: docker.io/library/golang:alpine

.go_rules:
  rules:
    - changes: 
      - "**/*.go"

before_script:
  - go version
  # golang.org/issues/61888
  - rm -f go.mod
  - go mod init gitlab.com/nzv/prc

stages:
  - go-check
  # https://go.dev/doc/devel/release#policy
  - test
  - report

go-check:
  script:
    - go run golang.org/x/vuln/cmd/govulncheck@latest
    # golang.org/issues/24230
    - test -z $(gofmt -l .)
    - go vet ./...
  rules:
    - !reference [.go_rules, rules]

go-test 1/3:
  stage: test
  image: docker.io/library/golang:1.20-alpine
  script:
    - go test ./...
  rules:
    - !reference [.go_rules, rules]

go-test 2/3:
  stage: test
  image: docker.io/library/golang:1.21-alpine
  script:
    - go test ./...
  rules:
    - !reference [.go_rules, rules]

go-test 3/3:
  stage: test
  script:
    - go test ./...
  rules:
    - !reference [.go_rules, rules]

do-report:
  stage: report
  script:
    - go test -run=TestGenerateReport
  artifacts:
    paths:
      - REPORT.csv
