# Copyright 2023 Enzo Venturi. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

default:
  image: docker.io/library/golang:alpine

before_script:
  - go version
  # golang.org/issues/61888
  - rm -f go.mod
  - go mod init gitlab.com/nzv/prc

stages:
  - go-check
  # https://go.dev/doc/devel/release#policy
  - test
  - report

go-check:
  script:
    - go run golang.org/x/vuln/cmd/govulncheck@latest
    # golang.org/issues/24230
    - test -z $(gofmt -l .)
    - go vet ./...

go-test 1/3:
  stage: test
  image: docker.io/library/golang:1.20-alpine
  script:
    - go test ./...

go-test 2/3:
  stage: test
  image: docker.io/library/golang:1.21-alpine
  script:
    - go test ./...

go-test 3/3:
  stage: test
  script:
    - go test ./...

do-report:
  stage: report
  script:
    - |
      apk add --no-cache git
      go test -run=TestGenerateReport
      git config --global user.name  "prc-reporter"
      git config --global user.email "no-reply@gitlab.com"
      git remote add ci-origin https://oauth2:${CI_REPORTER_TOKEN}@gitlab.com/nzv/prc.git
      git add REPORT
      git commit --message "cicd: run gotest 'TestGenerateReport'"
      git push -o ci.skip ci-origin main
